version: '3'
services:
  web:
    build:
      context: .
      target: build-stage
    restart: always
    image: nars:latest
    container_name: nars
    command: npm run serve
    ports:
      - "8080:8080"
    volumes:
      - .:/app

